### ISSUE TITLE
Your dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by k-goncharova** [marovski/covid19cvdata#2]
Hello,

Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/PQK1YP

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by marovski** [comment]
Hello!

Yes, it will be a pleasure to contribute to the CoronaWhy project.

Regards.

**Comment by k-goncharova** [comment]
Great, thank you. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the Dataset creator permissions to your dataset. Then please add relevant metadata - description and keywords to your dataset. 

Additionally, you may want join our community of 1,000+ contributors in Slack https://www.coronawhy.org/join-the-fight and see if any other initiatives could be interesting to you. We have many cool staff going on :)

**Comment by marovski** [comment]
Great! I will join the fight ;)

My account username is marovski.

**Comment by k-goncharova** [comment]
Super :) Permissions for editing were granted to you. Here is an example of dataset with good metadata for the reference https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TZMOTL. If you could start with the update of description and keywords for your dataset, that would be helpful.

**Comment by k-goncharova** [comment]
Hi @marovski, thanks for submitting the updated dataset for review. Would you be able to add metadata like description and key words to it? That will make it easier to find. You can check this dataset as an example of more detailed metadata https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TZMOTL
